<?php 
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('bulkexport-csv') . '?total=' . $this->total);
$form->setAttribute('method', 'post');

$defFields = explode(',', $this->defFields);
$defLabels = array();

foreach ($defFields as $field){
	array_push($defLabels, $this->transEsc($field));
}

$selFields = explode(',', $this->selFields);
$selLabels = array();

foreach ($selFields as $field){
	array_push($selLabels, $this->transEsc($field));
}

$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);
?>

<div>
	<h2><?=$this->transEsc('export_csv')?></h2>
</div>

<div style="margin-bottom:10px" class="select">
<?php
	echo $formLabel->openTag() . $this->transEsc('default_fields') . implode(', ', $defLabels) . '.<br>' . $this->transEsc('select_fields');
	echo $formLabel->closeTag();
	$fields = $form->get('fields');
	$fields->setValueOptions($selLabels);
    echo $this->formSelect($fields);
    echo $this->formElementErrors($fields);  
?></div>

<div style="margin-bottom:20px" class="checkbox-inline">
<?php
    $abstract = $form->get('abstract');
	echo $this->formCheckbox($abstract);
    echo $this->formElementErrors($abstract);
	echo $formLabel->openTag() . $this->transEsc('include_abstract');
    echo $formLabel->closeTag();
?></div>

<div style="margin-bottom:20px" class="select">
<?php
    $os = $form->get('os');
	echo $formLabel->openTag() . $this->transEsc('operating_system');
    echo $this->formSelect($os);
    echo $this->formElementErrors($os);
    echo $formLabel->closeTag();
?></div>

<div style="margin-bottom:20px" class="form_element">
<?php
    $email = $form->get('email');
	echo $formLabel->openTag() . $this->transEsc('email_address');
    echo $this->formEmail($email);
    echo $this->formElementErrors($email);
    echo $formLabel->closeTag();
?></div>

<div style="margin-bottom:20px" class="form_element">
<?php
    $captcha = $form->get('captcha');
    echo $this->formCaptcha($captcha);
    echo $this->formElementErrors($captcha);
    echo $formLabel->closeTag();
?></div>

<div style="margin-bottom:20px">
	<?=$this->formElement($form->get('send')) ?>
</div>

<?=$this->form()->closeTag() ?>